### ISSUE TITLE
Able to be used for Resident Evil 7 ?

### ISSUE THREAD

**Issue by linkthehylian** [ThirteenAG/DyingLight.BorderlessWindowedMode#3]
I just wanted to know if it's possible to use your Infinite Ammo mod and Dying Light Borderless Windowed mode on Resident Evil 7 since it doesn't have a borderless window option. I don't know if two ASI files can be loaded at once.

I don't know what I'm doing wrong here since nothing changes when I open the game.
![p3cydyc](https://user-images.githubusercontent.com/20933012/48462002-59ad9100-e7a4-11e8-8463-90db82046a0e.png)

![jpkfv8l](https://user-images.githubusercontent.com/20933012/48461988-4c90a200-e7a4-11e8-81cb-f213ee33b977.png)

**Comment by ThirteenAG** [comment]
No, it's game specific. I guess I can take a quick look if it's possible to do something similar for RE7.

**Comment by linkthehylian** [comment]
> No, it's game specific. I guess I can take a quick look if it's possible to do something similar for RE7.

That would be amazing, thank you!

**Comment by ThirteenAG** [comment]
RE7 already has borderless option, seems like demo doesn't have it, but it's possible to adjust Dying Light's code a bit to make it work. Try this plugin.
[RE7Demo.BorderlessWindowedMode.asi.zip](https://github.com/ThirteenAG/DyingLight.BorderlessWindowedMode/files/2585701/RE7Demo.BorderlessWindowedMode.asi.zip)
